version: '3.9'
services:
  countries-db:
    image: ash773/countries-db:0.0.1.RELEASE
    ports:
      - "5432:5432"
    restart: always
    networks:
      - countries-network

networks:
  countries-network: